import networkx as nx
g=nx.Graph()

g.add_node("Holly Lane 1")
g.add_node("Minden Way / Holly Lane 2")
g.add_node("Holly Lane 3")
g.add_node("The Chapel of Healing 4")
g.add_node("Adventurers Walk 5")
g.add_node("Adventurers Walk 6")
g.add_node("Adventurers Walk 7")
g.add_node("Foyer 8")
g.add_node("Main Road / Holly Lane 9")
g.add_node("Main Road / Wisden Street 10")
g.add_node("Main Road / Warrior's Walk 11")
g.add_node("Main Road / Dragon Road 12")
g.add_node("Dragon Road 13")
g.add_node("Dragon Road 14")
g.add_node("Danestrete / Warrior's Walk / Dragon Road 15")
g.add_node("Danestrete / Wisden Street 16")
g.add_node("Amber Gate / Danestrete 17")
g.add_node("Outside the town of Amethyst. 18")
g.add_node("Busy Junction. 19")
g.add_node("The Cartway 20")
g.add_node("The Cartway 21")
g.add_node("The Cartway 22")
g.add_node("The Cartway 23")
g.add_node("The Cartway 24")
g.add_node("Warrior's Walk 25")
g.add_node("Warrior's Walk 26")
g.add_node("Main Road 27")
g.add_node("Grey Street / Main Road 28")
g.add_node("The Arcade / Grey Street 29")
g.add_node("Foyer 30")
g.add_node("Balcony 31")
g.add_node("Waitress's Cubbyhole. 32")
g.add_node("Walkway 33")
g.add_node("Upper Seating. 34")
g.add_node("Walkway 35")
g.add_node("Lower Seating 36")
g.add_node("Backstage 37")
g.add_node("On the Stage 38")
g.add_node("Stage Right 39")
g.add_node("Behind the Stage 40")
g.add_node("Changing Room 41")
g.add_node("Grey Street 42")
g.add_node("Willan's Pawn Shop 43")
g.add_node("Danestrete / Grey Street 44")
g.add_node("Danestrete 45")
g.add_node("Town Tip 46")
g.add_node("The Farmers Gate / Dragon Road. 47")
g.add_node("Market Entrance 48")
g.add_node("Main thoroughfare. 49")
g.add_node("Livestock Auctions. 50")
g.add_node("Cattle Paddocks 51")
g.add_node("Stables. 52")
g.add_node("Foodplant Auctions. 53")
g.add_node("The General Market. 54")
g.add_node("The Corn Market. 55")
g.add_node("The Wheat Market. 56")
g.add_node("The Arcade / Wisden Street 57")
g.add_node("Wisden Street 58")
g.add_node("Traders Road 59")
g.add_node("Traders Road 60")
g.add_node("Traders Road 61")
g.add_node("Traders Road 62")
g.add_node("Traders Road 63")
g.add_node("Traders Road 64")
g.add_node("Traders Road 65")
g.add_node("Blackstar Bridge 66")
g.add_node("North of Amber. 67")
g.add_node("Amethyst Street 68")
g.add_node("Moldain Road / Amethyst Street 69")
g.add_node("Amethyst Street 70")
g.add_node("North Parade / Amethyst Street / Barber's Road 71")
g.add_node("The Bridge of Dreams 72")
g.add_node("The Watch Walls / Amethyst Street / Ashden Street 73")
g.add_node("The Watch Walls / Dominium Way 74")
g.add_node("The Watch Walls 75")
g.add_node("The Watch Walls 76")
g.add_node("The Watch Walls / Forest Walk 77")
g.add_node("Forest Walk 78")
g.add_node("Forest Walk / Dominium Way 79")
g.add_node("Barber's Road 80")
g.add_node("Barber's Road / Charter Avenue 81")
g.add_node("Barber's Road 82")
g.add_node("Barber's Road / Moldain Road 83")
g.add_node("Barber's Road 84")
g.add_node("Outside Amber 85")
g.add_node("Coral Road 86")
g.add_node("Coral Road 87")
g.add_node("Crossroads 88")
g.add_node("Amber Road 89")
g.add_node("Amber Road 90")
g.add_node("Amber Road 91")
g.add_node("South of Coral 92")
g.add_node("Coral High Street 93")
g.add_node("Coral High Street / Chalcyn Street / Brass Crescent 94")
g.add_node("Brass Crescent / Cardemon Way 95")
g.add_node("Cardemon Way 96")
g.add_node("Cardemon Way 97")
g.add_node("Coral High Street 98")
g.add_node("Coral High Street / Ondurin Road 99")
g.add_node("Coral High Street / Broom Walk 100")
g.add_node("Coral High Street / Brass Crescent 101")
g.add_node("North of Coral 102")
g.add_node("The Cartway Bridge 103")
g.add_node("Kelim's Trail 104")
g.add_node("Kelim's Trail 105")
g.add_node("Kelim's Trail 106")
g.add_node("Kelim's Trail 107")
g.add_node("Kelim's Trail 108")
g.add_node("Outside the village of HighMarket. 109")
g.add_node("Ironfounder's Road 110")
g.add_node("Amber Way 111")
g.add_node("Amber Way 112")
g.add_node("Amber Way 113")
g.add_node("Amber Way 114")
g.add_node("High Street 115")
g.add_node("High Street 116")
g.add_node("High Street 117")
g.add_node("Village Centre 118")
g.add_node("Ironfounder's Road 119")
g.add_node("Ironfounder's Road 120")
g.add_node("Ironfounder's Road 121")
g.add_node("Amber Road 122")
g.add_node("The Black Gate / Minden Way 123")
g.add_node("Outside the north gate of Amethyst 124")
g.add_node("The Fort Road 125")
g.add_node("Outside the Fort. 126")
g.add_node("South Gate 127")
g.add_node("Central Parade Ground. 128")
g.add_node("North Gate 129")
g.add_node("The Western Parade 130")
g.add_node("The Western Parade 131")
g.add_node("The Western Parade 132")
g.add_node("North of the Fort. 133")
g.add_node("Junction in the road. 134")
g.add_node("The Plains Road 135")
g.add_node("The Plains Road 136")
g.add_node("The South Plains Road 137")
g.add_node("The South Plains Road 138")
g.add_node("The South Plains Road 139")
g.add_node("The South Plains Road 140")
g.add_node("The South Plains Road 141")
g.add_node("The South Plains Road 142")
g.add_node("Village Street 143")
g.add_node("Village Street 144")
g.add_node("Village Street 145")
g.add_node("Village Street 146")
g.add_node("Village Street 147")
g.add_node("Outside Greenhaven 148")
g.add_node("The South Plains Road 149")
g.add_node("The South Plains Road 150")
g.add_node("The South Plains Road 151")
g.add_node("The South Plains Road 152")
g.add_node("Secret Trail 153")
g.add_node("Bandit Camp 154")

g.add_edge("Holly Lane 1", "Holly Lane 3", name="south")
g.add_edge("Holly Lane 1", "Minden Way / Holly Lane 2", name="north")
g.add_edge("Minden Way / Holly Lane 2", "The Black Gate / Minden Way 123", name="west")
g.add_edge("Minden Way / Holly Lane 2", "Holly Lane 1", name="south")
g.add_edge("Holly Lane 3", "Holly Lane 1", name="north")
g.add_edge("Holly Lane 3", "Main Road / Holly Lane 9", name="south")
g.add_edge("Holly Lane 3", "The Chapel of Healing 4", name="chapel")
g.add_edge("The Chapel of Healing 4", "Holly Lane 3", name="out")
g.add_edge("Main Road / Holly Lane 9", "Holly Lane 3", name="north")
g.add_edge("Main Road / Holly Lane 9", "Main Road 27", name="west")
g.add_edge("Main Road / Holly Lane 9", "Main Road / Wisden Street 10", name="east")
g.add_edge("Main Road / Wisden Street 10", "Main Road / Holly Lane 9", name="west")
g.add_edge("Main Road / Wisden Street 10", "Main Road / Warrior's Walk 11", name="east")
g.add_edge("Main Road / Wisden Street 10", "The Arcade / Wisden Street 57", name="south")
g.add_edge("Main Road / Warrior's Walk 11", "Main Road / Wisden Street 10", name="west")
g.add_edge("Main Road / Warrior's Walk 11", "Main Road / Dragon Road 12", name="east")
g.add_edge("Main Road / Dragon Road 12", "The Farmers Gate / Dragon Road. 47", name="north")
g.add_edge("Main Road / Dragon Road 12", "Main Road / Warrior's Walk 11", name="west")
g.add_edge("Dragon Road 13", "Main Road / Dragon Road 12", name="north")
g.add_edge("Dragon Road 14", "Dragon Road 13", name="north")
g.add_edge("Dragon Road 14", "Town Tip 46", name="tip")
g.add_edge("Danestrete / Warrior's Walk / Dragon Road 15", "Dragon Road 14", name="northeast")
g.add_edge("Danestrete / Wisden Street 16", "Wisden Street 58", name="north")
g.add_edge("Danestrete / Wisden Street 16", "Amber Gate / Danestrete 17", name="west")
g.add_edge("Danestrete / Wisden Street 16", "Danestrete / Warrior's Walk / Dragon Road 15", name="east")
g.add_edge("Amber Gate / Danestrete 17", "Danestrete / Wisden Street 16", name="east")
g.add_edge("Amber Gate / Danestrete 17", "Outside the town of Amethyst. 18", name="gate")
g.add_edge("Outside the town of Amethyst. 18", "Amber Gate / Danestrete 17", name="gate")
g.add_edge("Outside the town of Amethyst. 18", "Busy Junction. 19", name="south")
g.add_edge("Busy Junction. 19", "Outside the town of Amethyst. 18", name="north")
g.add_edge("Busy Junction. 19", "Traders Road 59", name="south")
g.add_edge("The Cartway 20", "Busy Junction. 19", name="northwest")
g.add_edge("The Cartway 21", "The Cartway 20", name="northwest")
g.add_edge("The Cartway 22", "The Cartway 21", name="west")
g.add_edge("The Cartway 23", "The Cartway 22", name="west")
g.add_edge("The Cartway 23", "Kelim's Trail 104", name="pathway")
g.add_edge("The Cartway 24", "The Cartway 20", name="northwest")
g.add_edge("Main Road 27", "Grey Street / Main Road 28", name="west")
g.add_edge("Main Road 27", "Main Road / Holly Lane 9", name="east")
g.add_edge("Grey Street / Main Road 28", "The Arcade / Grey Street 29", name="south")
g.add_edge("Grey Street / Main Road 28", "Main Road 27", name="east")
g.add_edge("The Arcade / Grey Street 29", "Grey Street / Main Road 28", name="north")
g.add_edge("The Arcade / Grey Street 29", "Grey Street 42", name="south")
g.add_edge("Foyer 30", "The Arcade / Grey Street 29", name="out")
g.add_edge("Balcony 31", "Foyer 30", name="down")
g.add_edge("Waitress's Cubbyhole. 32", "Balcony 31", name="out")
g.add_edge("Walkway 33", "Foyer 30", name="out")
g.add_edge("Walkway 33", "Walkway 35", name="down")
g.add_edge("Upper Seating. 34", "Walkway 33", name="out")
g.add_edge("Walkway 35", "Walkway 33", name="up")
g.add_edge("Walkway 35", "Backstage 37", name="door")
g.add_edge("Lower Seating 36", "Walkway 35", name="out")
g.add_edge("Backstage 37", "Walkway 35", name="door")
g.add_edge("Backstage 37", "On the Stage 38", name="stage")
g.add_edge("On the Stage 38", "Backstage 37", name="side")
g.add_edge("On the Stage 38", "Stage Right 39", name="side 2")
g.add_edge("Stage Right 39", "On the Stage 38", name="stage")
g.add_edge("Stage Right 39", "Behind the Stage 40", name="backstage")
g.add_edge("Behind the Stage 40", "Changing Room 41", name="door")
g.add_edge("Changing Room 41", "Behind the Stage 40", name="out")
g.add_edge("Grey Street 42", "Danestrete / Grey Street 44", name="southeast")
g.add_edge("Grey Street 42", "Willan's Pawn Shop 43", name="shop")
g.add_edge("Willan's Pawn Shop 43", "Grey Street 42", name="out")
g.add_edge("Danestrete / Grey Street 44", "Danestrete 45", name="east")
g.add_edge("Danestrete 45", "Amber Gate / Danestrete 17", name="east")
g.add_edge("Town Tip 46", "Dragon Road 14", name="out")
g.add_edge("The Farmers Gate / Dragon Road. 47", "Main Road / Dragon Road 12", name="south")
g.add_edge("The Farmers Gate / Dragon Road. 47", "Market Entrance 48", name="west")
g.add_edge("Market Entrance 48", "The Farmers Gate / Dragon Road. 47", name="out")
g.add_edge("Market Entrance 48", "Main thoroughfare. 49", name="west")
g.add_edge("Main thoroughfare. 49", "Market Entrance 48", name="east")
g.add_edge("Main thoroughfare. 49", "Livestock Auctions. 50", name="north")
g.add_edge("Main thoroughfare. 49", "Foodplant Auctions. 53", name="west")
g.add_edge("Livestock Auctions. 50", "Main thoroughfare. 49", name="south")
g.add_edge("Livestock Auctions. 50", "Stables. 52", name="west")
g.add_edge("Livestock Auctions. 50", "Cattle Paddocks 51", name="north")
g.add_edge("Cattle Paddocks 51", "Livestock Auctions. 50", name="south")
g.add_edge("Stables. 52", "Livestock Auctions. 50", name="east")
g.add_edge("Foodplant Auctions. 53", "Main thoroughfare. 49", name="east")
g.add_edge("Foodplant Auctions. 53", "The General Market. 54", name="south")
g.add_edge("Foodplant Auctions. 53", "The Corn Market. 55", name="west")
g.add_edge("Foodplant Auctions. 53", "The Wheat Market. 56", name="north")
g.add_edge("The General Market. 54", "Foodplant Auctions. 53", name="north")
g.add_edge("The Corn Market. 55", "Foodplant Auctions. 53", name="east")
g.add_edge("The Wheat Market. 56", "Foodplant Auctions. 53", name="south")
g.add_edge("The Arcade / Wisden Street 57", "Main Road / Wisden Street 10", name="north")
g.add_edge("The Arcade / Wisden Street 57", "Wisden Street 58", name="south")
g.add_edge("Wisden Street 58", "The Arcade / Wisden Street 57", name="north")
g.add_edge("Wisden Street 58", "Danestrete / Wisden Street 16", name="south")
g.add_edge("Traders Road 59", "Traders Road 60", name="southwest")
g.add_edge("Traders Road 60", "Traders Road 61", name="southwest")
g.add_edge("Traders Road 61", "Traders Road 62", name="south")
g.add_edge("Traders Road 62", "North of Amber. 67", name="south")
g.add_edge("Traders Road 63", "Traders Road 64", name="southwest")
g.add_edge("Traders Road 64", "Traders Road 65", name="southeast")
g.add_edge("Traders Road 65", "Blackstar Bridge 66", name="south")
g.add_edge("Blackstar Bridge 66", "Traders Road 62", name="south")
g.add_edge("North of Amber. 67", "Amethyst Street 68", name="south")
g.add_edge("Amethyst Street 68", "Moldain Road / Amethyst Street 69", name="south")
g.add_edge("Moldain Road / Amethyst Street 69", "Amethyst Street 70", name="south")
g.add_edge("Amethyst Street 70", "North Parade / Amethyst Street / Barber's Road 71", name="south")
g.add_edge("North Parade / Amethyst Street / Barber's Road 71", "The Bridge of Dreams 72", name="south")
g.add_edge("North Parade / Amethyst Street / Barber's Road 71", "Barber's Road 80", name="east")
g.add_edge("The Bridge of Dreams 72", "North Parade / Amethyst Street / Barber's Road 71", name="north")
g.add_edge("The Bridge of Dreams 72", "The Watch Walls / Amethyst Street / Ashden Street 73", name="south")
g.add_edge("The Watch Walls / Amethyst Street / Ashden Street 73", "The Bridge of Dreams 72", name="north")
g.add_edge("The Watch Walls / Amethyst Street / Ashden Street 73", "The Watch Walls / Dominium Way 74", name="west")
g.add_edge("The Watch Walls / Dominium Way 74", "The Watch Walls 75", name="west")
g.add_edge("The Watch Walls / Dominium Way 74", "The Watch Walls / Amethyst Street / Ashden Street 73", name="east")
g.add_edge("The Watch Walls 75", "The Watch Walls 76", name="west")
g.add_edge("The Watch Walls 75", "The Watch Walls / Dominium Way 74", name="east")
g.add_edge("The Watch Walls 76", "The Watch Walls / Forest Walk 77", name="west")
g.add_edge("The Watch Walls 76", "The Watch Walls 75", name="east")
g.add_edge("The Watch Walls / Forest Walk 77", "Forest Walk 78", name="north")
g.add_edge("The Watch Walls / Forest Walk 77", "The Watch Walls 76", name="east")
g.add_edge("Forest Walk 78", "Forest Walk / Dominium Way 79", name="north")
g.add_edge("Forest Walk 78", "The Watch Walls / Forest Walk 77", name="south")
g.add_edge("Forest Walk / Dominium Way 79", "Forest Walk 78", name="south")
g.add_edge("Barber's Road 80", "Barber's Road / Charter Avenue 81", name="east")
g.add_edge("Barber's Road / Charter Avenue 81", "Barber's Road 82", name="east")
g.add_edge("Barber's Road 82", "Barber's Road / Moldain Road 83", name="east")
g.add_edge("Barber's Road / Moldain Road 83", "Barber's Road 84", name="east")
g.add_edge("Barber's Road 84", "Outside Amber 85", name="east")
g.add_edge("Outside Amber 85", "Coral Road 86", name="east")
g.add_edge("Coral Road 86", "Coral Road 87", name="east")
g.add_edge("Coral Road 87", "Crossroads 88", name="northeast")
g.add_edge("Crossroads 88", "Amber Road 89", name="east")
g.add_edge("Amber Road 89", "Amber Road 122", name="northeast")
g.add_edge("Amber Road 90", "Amber Road 91", name="northeast")
g.add_edge("Amber Road 91", "South of Coral 92", name="northeast")
g.add_edge("South of Coral 92", "Coral High Street 93", name="north")
g.add_edge("Coral High Street 93", "North of Coral 102", name="north")
g.add_edge("Coral High Street / Chalcyn Street / Brass Crescent 94", "Coral High Street 98", name="north")
g.add_edge("Coral High Street / Chalcyn Street / Brass Crescent 94", "Brass Crescent / Cardemon Way 95", name="west")
g.add_edge("Brass Crescent / Cardemon Way 95", "Coral High Street / Chalcyn Street / Brass Crescent 94", name="east")
g.add_edge("Brass Crescent / Cardemon Way 95", "Cardemon Way 96", name="south")
g.add_edge("Cardemon Way 96", "Brass Crescent / Cardemon Way 95", name="north")
g.add_edge("Cardemon Way 96", "Cardemon Way 97", name="southwest")
g.add_edge("Cardemon Way 97", "Cardemon Way 96", name="northeast")
g.add_edge("Coral High Street 98", "Coral High Street / Broom Walk 100", name="north")
g.add_edge("Coral High Street / Ondurin Road 99", "Coral High Street 93", name="north")
g.add_edge("Coral High Street / Broom Walk 100", "Coral High Street / Brass Crescent 101", name="north")
g.add_edge("Coral High Street / Brass Crescent 101", "Coral High Street 93", name="north")
g.add_edge("North of Coral 102", "The Cartway Bridge 103", name="north")
g.add_edge("The Cartway Bridge 103", "The Cartway 24", name="northwest")
g.add_edge("Kelim's Trail 104", "Kelim's Trail 105", name="northwest")
g.add_edge("Kelim's Trail 104", "The Cartway 23", name="south")
g.add_edge("Kelim's Trail 105", "Kelim's Trail 106", name="north")
g.add_edge("Kelim's Trail 105", "Kelim's Trail 104", name="southeast")
g.add_edge("Kelim's Trail 106", "Outside the village of HighMarket. 109", name="north")
g.add_edge("Kelim's Trail 106", "Kelim's Trail 105", name="south")
g.add_edge("Kelim's Trail 107", "Kelim's Trail 108", name="northwest")
g.add_edge("Kelim's Trail 107", "Kelim's Trail 106", name="south")
g.add_edge("Kelim's Trail 108", "Kelim's Trail 105", name="northwest")
g.add_edge("Kelim's Trail 108", "Kelim's Trail 107", name="southeast")
g.add_edge("Outside the village of HighMarket. 109", "Kelim's Trail 106", name="south")
g.add_edge("Outside the village of HighMarket. 109", "Ironfounder's Road 110", name="gate")
g.add_edge("Ironfounder's Road 110", "Amber Way 111", name="west")
g.add_edge("Ironfounder's Road 110", "Outside the village of HighMarket. 109", name="gate")
g.add_edge("Amber Way 111", "Amber Way 112", name="north")
g.add_edge("Amber Way 112", "Amber Way 113", name="northwest")
g.add_edge("Amber Way 113", "Amber Way 114", name="northwest")
g.add_edge("Amber Way 114", "High Street 115", name="north")
g.add_edge("High Street 115", "High Street 116", name="east")
g.add_edge("High Street 116", "High Street 117", name="east")
g.add_edge("High Street 117", "Village Centre 118", name="east")
g.add_edge("Village Centre 118", "Ironfounder's Road 119", name="south")
g.add_edge("Ironfounder's Road 119", "Ironfounder's Road 120", name="south")
g.add_edge("Ironfounder's Road 120", "Ironfounder's Road 121", name="south")
g.add_edge("Ironfounder's Road 121", "Ironfounder's Road 110", name="south")
g.add_edge("Amber Road 122", "Amber Road 90", name="northeast")
g.add_edge("The Black Gate / Minden Way 123", "Minden Way / Holly Lane 2", name="east")
g.add_edge("Outside the north gate of Amethyst 124", "The Black Gate / Minden Way 123", name="gate")
g.add_edge("Outside the north gate of Amethyst 124", "The Fort Road 125", name="north")
g.add_edge("The Fort Road 125", "Outside the north gate of Amethyst 124", name="south")
g.add_edge("The Fort Road 125", "Outside the Fort. 126", name="north")
g.add_edge("Outside the Fort. 126", "The Fort Road 125", name="south")
g.add_edge("Outside the Fort. 126", "South Gate 127", name="gate")
g.add_edge("South Gate 127", "Central Parade Ground. 128", name="north")
g.add_edge("South Gate 127", "Outside the Fort. 126", name="gate")
g.add_edge("Central Parade Ground. 128", "North Gate 129", name="north")
g.add_edge("Central Parade Ground. 128", "The Western Parade 131", name="west")
g.add_edge("Central Parade Ground. 128", "South Gate 127", name="south")
g.add_edge("North Gate 129", "The Western Parade 130", name="west")
g.add_edge("North Gate 129", "Central Parade Ground. 128", name="south")
g.add_edge("North Gate 129", "North of the Fort. 133", name="gate")
g.add_edge("The Western Parade 130", "The Western Parade 131", name="south")
g.add_edge("The Western Parade 131", "Central Parade Ground. 128", name="east")
g.add_edge("The Western Parade 131", "The Western Parade 132", name="south")
g.add_edge("The Western Parade 132", "South Gate 127", name="east")
g.add_edge("North of the Fort. 133", "North Gate 129", name="gate")
g.add_edge("North of the Fort. 133", "Junction in the road. 134", name="north")
g.add_edge("Junction in the road. 134", "The Plains Road 135", name="northwest")
g.add_edge("Junction in the road. 134", "North of the Fort. 133", name="south")
g.add_edge("The Plains Road 135", "Junction in the road. 134", name="southeast")
g.add_edge("The Plains Road 135", "The Plains Road 136", name="northwest")
g.add_edge("The Plains Road 136", "The Plains Road 135", name="southeast")
g.add_edge("The Plains Road 136", "The South Plains Road 137", name="southwest")
g.add_edge("The South Plains Road 137", "The Plains Road 136", name="northeast")
g.add_edge("The South Plains Road 137", "The South Plains Road 140", name="southwest")
g.add_edge("The South Plains Road 138", "The South Plains Road 137", name="northeast")
g.add_edge("The South Plains Road 138", "The South Plains Road 139", name="south")
g.add_edge("The South Plains Road 139", "The South Plains Road 138", name="north")
g.add_edge("The South Plains Road 139", "The South Plains Road 137", name="southwest")
g.add_edge("The South Plains Road 140", "The South Plains Road 137", name="northeast")
g.add_edge("The South Plains Road 140", "The South Plains Road 141", name="west")
g.add_edge("The South Plains Road 141", "The South Plains Road 140", name="east")
g.add_edge("The South Plains Road 141", "The South Plains Road 142", name="west")
g.add_edge("The South Plains Road 142", "The South Plains Road 141", name="east")
g.add_edge("The South Plains Road 142", "Village Street 143", name="southwest")
g.add_edge("Village Street 143", "Village Street 144", name="southwest")
g.add_edge("Village Street 143", "The South Plains Road 142", name="northeast")
g.add_edge("Village Street 144", "Village Street 143", name="northeast")
g.add_edge("Village Street 144", "Village Street 145", name="southwest")
g.add_edge("Village Street 145", "Village Street 144", name="northeast")
g.add_edge("Village Street 145", "Village Street 146", name="southwest")
g.add_edge("Village Street 146", "Village Street 145", name="northeast")
g.add_edge("Village Street 146", "Village Street 147", name="southwest")
g.add_edge("Village Street 147", "Village Street 146", name="northeast")
g.add_edge("Village Street 147", "Outside Greenhaven 148", name="southwest")
g.add_edge("Outside Greenhaven 148", "Village Street 147", name="northeast")
g.add_edge("Outside Greenhaven 148", "The South Plains Road 141", name="west")
g.add_edge("The South Plains Road 149", "The South Plains Road 141", name="east")
g.add_edge("The South Plains Road 149", "The South Plains Road 150", name="northwest")
g.add_edge("The South Plains Road 150", "The South Plains Road 149", name="southeast")
g.add_edge("The South Plains Road 150", "The South Plains Road 141", name="west")
g.add_edge("The South Plains Road 151", "The South Plains Road 149", name="southeast")
g.add_edge("The South Plains Road 151", "The South Plains Road 152", name="southwest")
g.add_edge("The South Plains Road 152", "The South Plains Road 151", name="northeast")
g.add_edge("The South Plains Road 152", "The South Plains Road 150", name="northwest")
g.add_edge("Secret Trail 153", "The South Plains Road 142", name="north")
g.add_edge("Secret Trail 153", "Bandit Camp 154", name="south")
g.add_edge("Bandit Camp 154", "Secret Trail 153", name="north")